import { ArtworkType } from '../@types';

export const RATING_LABELS: { [index: string]: string } = {
  0.5: 'Useless',
  1: 'Useless+',
  1.5: 'Poor',
  2: 'Poor+',
  2.5: 'Fine',
  3: 'Pretty good',
  3.5: 'Good!',
  4: 'Great!',
  4.5: 'Incredible',
  5: 'Transcendent',
};

export const defaultList: ArtworkType[] = [
  {
    objectID: 485308,
    isHighlight: true,
    accessionNumber: '1989.349',
    accessionYear: '1989',
    isPublicDomain: false,
    primaryImage: '',
    primaryImageSmall: '',
    additionalImages: [],
    constituents: [
      {
        constituentID: 164422,
        role: 'Artist',
        name: 'Joan Mitchell',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500000901',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q469934',
        gender: 'Female',
      },
    ],
    department: 'Modern and Contemporary Art',
    objectName: 'Painting',
    title: 'Sunflower',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Joan Mitchell',
    artistDisplayBio: 'American, Chicago, Illinois 1925–1992 Paris',
    artistSuffix: '',
    artistAlphaSort: 'Mitchell, Joan',
    artistNationality: 'American',
    artistBeginDate: '1925',
    artistEndDate: '1992',
    artistGender: 'Female',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q469934',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500000901',
    objectDate: '1969',
    objectBeginDate: 1969,
    objectEndDate: 1969,
    medium: 'Oil on canvas',
    dimensions: '102 1/4 in. × 70 3/4 in. (259.7 × 179.7 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 259.7155,
          Width: 179.70535,
        },
      },
      {
        elementName: 'Frame',
        elementDescription: null,
        elementMeasurements: {
          Depth: 7.620015,
          Height: 267.01804,
          Width: 187.32538,
        },
      },
    ],
    creditLine: 'Gift of Pierre Matisse, 1989',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-31T04:54:36.6Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/485308',
    tags: [
      {
        term: 'Sunflowers',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300404749',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q171497',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19922136',
    isTimelineWork: false,
    GalleryNumber: '',
  },
  {
    objectID: 700610,
    isHighlight: true,
    accessionNumber: '2016.4',
    accessionYear: '2016',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ad/original/DP-14225-001.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ad/web-large/DP-14225-001.jpg',
    additionalImages: [],
    constituents: [
      {
        constituentID: 182548,
        role: 'Artist',
        name: 'Charles Ethan Porter',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500122066',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q5077434',
        gender: '',
      },
    ],
    department: 'The American Wing',
    objectName: 'Watercolor',
    title: 'Still Life with Corn',
    culture: 'American',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Charles Ethan Porter',
    artistDisplayBio: '1847–1923',
    artistSuffix: '',
    artistAlphaSort: 'Porter, Charles Ethan',
    artistNationality: 'American',
    artistBeginDate: '1847',
    artistEndDate: '1923',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q5077434',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500122066',
    objectDate: 'ca. 1880',
    objectBeginDate: 1880,
    objectEndDate: 1880,
    medium: 'Watercolor on paper',
    dimensions: '10 1/2 × 17 in. (26.7 × 43.2 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 26.670053,
          Width: 43.180088,
        },
      },
      {
        elementName: 'Mat',
        elementDescription: null,
        elementMeasurements: {
          Height: 55.88011,
          Width: 71.12014,
        },
      },
    ],
    creditLine:
      'Purchase, Marguerite and Frank A. Cosgrove Jr. Fund and Cordelia and Jesse Zanger and Bonnie Johnson Sacerdote Foundation Gifts, 2016',
    geographyType: 'Probably made in',
    city: '',
    state: 'Connecticut',
    county: '',
    country: 'United States',
    region: 'New England',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-30T04:54:21.21Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/700610',
    tags: [
      {
        term: 'Apples',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300266417',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q89',
      },
      {
        term: 'Still Life',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300015638',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q170571',
      },
      {
        term: 'Corn',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300375397',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q11575',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q96358075',
    isTimelineWork: false,
    GalleryNumber: '773',
  },
  {
    objectID: 761604,
    isHighlight: true,
    accessionNumber: '2017.310',
    accessionYear: '2017',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ad/original/DP-15482-003.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ad/web-large/DP-15482-003.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/ad/original/DP-15482-007.jpg',
      'https://images.metmuseum.org/CRDImages/ad/original/DP-15482-004.jpg',
      'https://images.metmuseum.org/CRDImages/ad/original/DP-15482-005.jpg',
      'https://images.metmuseum.org/CRDImages/ad/original/DP-15482-006.jpg',
    ],
    constituents: [
      {
        constituentID: 212630,
        role: 'Maker',
        name: 'Unrecorded  Edgefield District potter',
        constituentULAN_URL: '',
        constituentWikidata_URL: '',
        gender: '',
      },
      {
        constituentID: 204973,
        role: 'Manufacturer',
        name: 'Unknown Old Edgefield District Pottery',
        constituentULAN_URL: '',
        constituentWikidata_URL: '',
        gender: '',
      },
    ],
    department: 'The American Wing',
    objectName: 'Face jug',
    title: '',
    culture: 'American',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Maker',
    artistPrefix: '',
    artistDisplayName: 'Unrecorded  Edgefield District potter',
    artistDisplayBio: 'American',
    artistSuffix: '',
    artistAlphaSort: 'Unrecorded Edgefield District potter',
    artistNationality: 'American',
    artistBeginDate: '1800',
    artistEndDate: '1920',
    artistGender: '',
    artistWikidata_URL: '',
    artistULAN_URL: '',
    objectDate: 'ca. 1850–80',
    objectBeginDate: 1845,
    objectEndDate: 1855,
    medium: 'Alkaline-glazed stoneware with kaolin',
    dimensions: '10 1/4 in. (26 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 26.035051,
        },
      },
    ],
    creditLine: 'Purchase, Nancy Dunn Revocable Trust Gift, 2017',
    geographyType: 'Made in',
    city: '',
    state: 'South Carolina',
    county: 'Edgefield County',
    country: 'United States',
    region: 'South',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-30T04:54:21.21Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/761604',
    tags: [
      {
        term: 'Faces',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300251798',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q37017',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q104413130',
    isTimelineWork: false,
    GalleryNumber: '762',
  },
  {
    objectID: 437329,
    isHighlight: true,
    accessionNumber: '46.160',
    accessionYear: '1946',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ep/original/DP-29324-001.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ep/web-large/DP-29324-001.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/ep/original/LC-46_160-2.jpg',
      'https://images.metmuseum.org/CRDImages/ep/original/LC-46_160-3.jpg',
    ],
    constituents: [
      {
        constituentID: 162270,
        role: 'Artist',
        name: 'Nicolas Poussin',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500005036',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q41554',
        gender: '',
      },
    ],
    department: 'European Paintings',
    objectName: 'Painting',
    title: 'The Abduction of the Sabine Women',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Nicolas Poussin',
    artistDisplayBio: 'French, Les Andelys 1594–1665 Rome',
    artistSuffix: '',
    artistAlphaSort: 'Poussin, Nicolas',
    artistNationality: 'French',
    artistBeginDate: '1594',
    artistEndDate: '1665',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q41554',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500005036',
    objectDate: 'probably 1633–34',
    objectBeginDate: 1633,
    objectEndDate: 1634,
    medium: 'Oil on canvas',
    dimensions: '60 7/8 x 82 5/8 in. (154.6 x 209.9 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 154.6,
          Width: 209.9,
        },
      },
      {
        elementName: 'Frame',
        elementDescription: null,
        elementMeasurements: {
          Depth: 12.7,
          Height: 187.9604,
          Width: 247.0155,
        },
      },
      {
        elementName: 'Other',
        elementDescription: 'Painting and Frame',
        elementMeasurements: {
          Weight: 68.03955,
        },
      },
    ],
    creditLine: 'Harris Brisbane Dick Fund, 1946',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-30T04:54:21.21Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/437329',
    tags: [
      {
        term: 'Suffering',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300055184',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q5780945',
      },
      {
        term: 'Children',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025945',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q7569',
      },
      {
        term: 'Men',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025928',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q8441',
      },
      {
        term: 'Women',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025943',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q467',
      },
      {
        term: 'Horses',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300250148',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q726',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q19911410',
    isTimelineWork: true,
    GalleryNumber: '623',
  },
  {
    objectID: 436535,
    isHighlight: true,
    accessionNumber: '1993.132',
    accessionYear: '1993',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ep/web-large/DT1567.jpg',
    additionalImages: [
      'https://images.metmuseum.org/CRDImages/ep/original/LC-EP_1993_132_suppl_CH-004.jpg',
      'https://images.metmuseum.org/CRDImages/ep/original/LC-EP_1993_132_suppl_CH-003.jpg',
      'https://images.metmuseum.org/CRDImages/ep/original/LC-EP_1993_132_suppl_CH-002.jpg',
      'https://images.metmuseum.org/CRDImages/ep/original/LC-EP_1993_132_suppl_CH-001.jpg',
    ],
    constituents: [
      {
        constituentID: 161947,
        role: 'Artist',
        name: 'Vincent van Gogh',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500115588',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q5582',
        gender: '',
      },
    ],
    department: 'European Paintings',
    objectName: 'Painting',
    title: 'Wheat Field with Cypresses',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Vincent van Gogh',
    artistDisplayBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
    artistSuffix: '',
    artistAlphaSort: 'Gogh, Vincent van',
    artistNationality: 'Dutch',
    artistBeginDate: '1853',
    artistEndDate: '1890',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q5582',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500115588',
    objectDate: '1889',
    objectBeginDate: 1889,
    objectEndDate: 1889,
    medium: 'Oil on canvas',
    dimensions: '28 7/8 × 36 3/4 in. (73.2 × 93.4 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 73.34264,
          Width: 93.4,
        },
      },
      {
        elementName: 'Glazing',
        elementDescription: 'See Notes in Description',
        elementMeasurements: {
          Height: 75.24765,
          Width: 94.93269,
        },
      },
    ],
    creditLine: 'Purchase, The Annenberg Foundation Gift, 1993',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-31T04:54:36.6Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/436535',
    tags: [
      {
        term: 'Landscapes',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300132294',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q191163',
      },
      {
        term: 'Cypresses',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300343641',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q146911',
      },
      {
        term: 'Summer',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300133099',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q1313',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q18689458',
    isTimelineWork: true,
    GalleryNumber: '822',
  },
  {
    objectID: 436121,
    isHighlight: true,
    accessionNumber: '29.100.128',
    accessionYear: '1929',
    isPublicDomain: true,
    primaryImage:
      'https://images.metmuseum.org/CRDImages/ep/original/DP-25460-001.jpg',
    primaryImageSmall:
      'https://images.metmuseum.org/CRDImages/ep/web-large/DP-25460-001.jpg',
    additionalImages: [],
    constituents: [
      {
        constituentID: 161821,
        role: 'Artist',
        name: 'Edgar Degas',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500115194',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q46373',
        gender: '',
      },
    ],
    department: 'European Paintings',
    objectName: 'Painting',
    title: 'A Woman Seated beside a Vase of Flowers (Madame Paul Valpinçon?)',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Artist',
    artistPrefix: '',
    artistDisplayName: 'Edgar Degas',
    artistDisplayBio: 'French, Paris 1834–1917 Paris',
    artistSuffix: '',
    artistAlphaSort: 'Degas, Edgar',
    artistNationality: 'French',
    artistBeginDate: '1834',
    artistEndDate: '1917',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q46373',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500115194',
    objectDate: '1865',
    objectBeginDate: 1865,
    objectEndDate: 1865,
    medium: 'Oil on canvas',
    dimensions: '29 x 36 1/2 in. (73.7 x 92.7 cm)',
    measurements: [
      {
        elementName: 'Overall',
        elementDescription: null,
        elementMeasurements: {
          Height: 73.7,
          Width: 92.7,
        },
      },
      {
        elementName: 'Frame',
        elementDescription: null,
        elementMeasurements: {
          Depth: 12.065,
          Height: 97.7902,
          Width: 116.2052,
        },
      },
      {
        elementName: 'Glazing',
        elementDescription: null,
        elementMeasurements: {
          Height: 74.93015,
          Width: 93.66269,
        },
      },
    ],
    creditLine:
      'H. O. Havemeyer Collection, Bequest of Mrs. H. O. Havemeyer, 1929',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: 'Paintings',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2025-01-30T04:54:21.21Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/436121',
    tags: [
      {
        term: 'Pitchers',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300194765',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q132397',
      },
      {
        term: 'Women',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300025943',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q467',
      },
      {
        term: 'Flowers',
        AAT_URL: 'http://vocab.getty.edu/page/aat/300132399',
        Wikidata_URL: 'https://www.wikidata.org/wiki/Q506',
      },
    ],
    objectWikidata_URL: 'https://www.wikidata.org/wiki/Q3713914',
    isTimelineWork: true,
    GalleryNumber: '810',
  },
];

export const departments = [
  {
    departmentId: 1,
    displayName: 'American Decorative Arts',
  },
  {
    departmentId: 3,
    displayName: 'Ancient Near Eastern Art',
  },
  {
    departmentId: 5,
    displayName: 'Arts of Africa, Oceania, and the Americas',
  },
  {
    departmentId: 6,
    displayName: 'Asian Art',
  },
  {
    departmentId: 7,
    displayName: 'The Cloisters',
  },
  {
    departmentId: 8,
    displayName: 'The Costume Institute',
  },
  {
    departmentId: 9,
    displayName: 'Drawings and Prints',
  },
  {
    departmentId: 10,
    displayName: 'Egyptian Art',
  },
  {
    departmentId: 11,
    displayName: 'European Paintings',
  },
  {
    departmentId: 12,
    displayName: 'European Sculpture and Decorative Arts',
  },
  {
    departmentId: 13,
    displayName: 'Greek and Roman Art',
  },
  {
    departmentId: 14,
    displayName: 'Islamic Art',
  },
  {
    departmentId: 15,
    displayName: 'The Robert Lehman Collection',
  },
  {
    departmentId: 16,
    displayName: 'The Libraries',
  },
  {
    departmentId: 17,
    displayName: 'Medieval Art',
  },
  {
    departmentId: 18,
    displayName: 'Musical Instruments',
  },
  {
    departmentId: 19,
    displayName: 'Photographs',
  },
  {
    departmentId: 21,
    displayName: 'Modern Art',
  },
];

export const SEARCH_URL =
  'https://collectionapi.metmuseum.org/public/collection/v1/search?';

export const GET_URL =
  'https://collectionapi.metmuseum.org/public/collection/v1/objects?';

export enum SEARCH_PARAMS {
  DEPARTMENT = 'departmentId',
  DEPARTMENTS = 'departmentIds',
}

export const OBJECTS_URL =
  'https://collectionapi.metmuseum.org/public/collection/v1/objects';
